### ISSUE TITLE
Responsive rows when using views

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/digital_agency#3]
Testing digital_agency with projects, services, testimonials the rows are all behaving responsively.

I like how you have them working with different views grid settings.

**Comment by izmeez** [comment]
@stpaultim In your previous comment, https://github.com/backdrop-contrib/zeever/issues/12#issuecomment-2159247545 you explained,

> The Digital Agency recipe includes some CSS to fix things and make some of the other recipes responsive. The Digital Services recipe can not be disabled without loosing these features.

> So the Services Recipe will only be responsive when use with a Recipe Package such as Digital Services or another theme that supports it.

> I think that is the best we can do for now. Unless we make changes to Basis, which has proven very problematic.

**Comment by izmeez** [comment]
@stpaultim Also from a previous comment of yours,

> I have made some tweaks to the CSS provided by the Digital Agency Recipe Package that will ensure that if one simply changes the view for this feature to 2, 4, 5, or 6 columns, the grid should still look good and be responsive.

**Comment by stpaultim** [comment]
As we have discussed here in the issue queue and as I have discussed with in many individual conversations. I'm still struggling a bit to find the best place to store CSS. Should it be in Recipes, Recipes Bundles, Seperate CSS modules, in configuration for something like CSS injector, or only in themes?

I just experimented with using CSS Injector for the css, but I don't think that will work, because it seems that CSS injector stores CSS in database, not in config files.

@klonos

**Comment by izmeez** [comment]
@stpaultim 
> I'm still struggling a bit to find the best place to store CSS. Should it be in Recipes, Recipes Bundles, Seperate CSS modules, in configuration for something like CSS injector, or only in themes?

What you have done helps to shed light on breaking this down. There is a common thread here. Each of the rows, while they have different purposes and content, have the same architecture: they are a series of blocks with a behaviour. 

Looking at Bootstrap there are some common patterns of behaviour:
1. Often with a series of items the responsive action is for items on the right to drop below. This is "standard" although sometimes having the element on the right moving above those on the left may be desired.
2. Depending on the number of items and the width, within a row, on a narrow display the last item(s) may be shortened number than those above and may look better if centered.

This does not answer the question, where should the css reside? But, this project may help to factor the problem.

**Comment by stpaultim** [comment]
> This does not answer the question, where should the css reside? But, this project may help to factor the problem.

Yes, that is correct. This is very much a learning project for me and I'm happy to share that learnign process with anyone else in the community that is interested. It's part of the reason that I'm thinking "out loud" as I make decisions. One, because it helps me to think out loud, but also so that others can participate in the process, learn from it, and make it better.
